model_list:
  - model_name: groq-llama3-8b-8192
    litellm_params:
      model: groq/llama3-8b-8192
      api_key: "[replace-with-your-groq-key]"
  - model_name: deepseek-r1-distill-llama-70b
    litellm_params:
      model: groq/deepseek-r1-distill-llama-70b
      api_key: "[replace-with-your-groq-key]"
